'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site

    '''<summary>
    '''HyperLinkSkipToMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkSkipToMain As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLinkSkipToAbout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkSkipToAbout As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LocalizeGcwuSig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocalizeGcwuSig As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''LocalizeLanguageSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocalizeLanguageSelection As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''HyperLinkLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkLanguage As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LocalizeSearchAndMenus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocalizeSearchAndMenus As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''HyperLinkSearchAndMenus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkSearchAndMenus As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HyperLinkHome1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkHome1 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LocalizeYouAreHere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocalizeYouAreHere As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''HyperLinkHome2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkHome2 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''contentPlaceHolderBreadCrumb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contentPlaceHolderBreadCrumb As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''contentPlaceHolderMainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contentPlaceHolderMainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''LocalizeDateModified control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocalizeDateModified As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''LocalizeAboutSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocalizeAboutSite As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''HyperLinkTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkTerms As Global.System.Web.UI.WebControls.HyperLink
End Class
